.ALIASES
V_V1            V1(+=N00855 -=0 ) CN @HW2_Q2_3.SCHEMATIC1(sch_1):INS891@SOURCE.VDC.Normal(chips)
C_C2            C2(1=N00855 2=V ) CN @HW2_Q2_3.SCHEMATIC1(sch_1):INS837@ANALOG.C.Normal(chips)
R_R2            R2(1=0 2=V ) CN @HW2_Q2_3.SCHEMATIC1(sch_1):INS911@ANALOG.R.Normal(chips)
C_C1            C1(1=0 2=V ) CN @HW2_Q2_3.SCHEMATIC1(sch_1):INS931@ANALOG.C.Normal(chips)
_    _(V=V)
.ENDALIASES
