.ALIASES
C_C1            C1(1=0 2=V ) CN @HW2_Q2_1.SCHEMATIC1(sch_1):INS26@ANALOG.C.Normal(chips)
C_C2            C2(1=N00130 2=V ) CN @HW2_Q2_1.SCHEMATIC1(sch_1):INS42@ANALOG.C.Normal(chips)
R_R2            R2(1=0 2=V ) CN @HW2_Q2_1.SCHEMATIC1(sch_1):INS83@ANALOG.R.Normal(chips)
V_V1            V1(+=N00130 -=0 ) CN @HW2_Q2_1.SCHEMATIC1(sch_1):INS761@SOURCE.VDC.Normal(chips)
_    _(V=V)
.ENDALIASES
