.ALIASES
R_R1            R1(1=N00124 2=V ) CN @HW2_Q1.SCHEMATIC1(sch_1):INS26@ANALOG.R.Normal(chips)
R_R2            R2(1=0 2=N00157 ) CN @HW2_Q1.SCHEMATIC1(sch_1):INS42@ANALOG.R.Normal(chips)
L_L1            L1(1=0 2=V ) CN @HW2_Q1.SCHEMATIC1(sch_1):INS67@ANALOG.L.Normal(chips)
L_L2            L2(1=N00157 2=N00124 ) CN @HW2_Q1.SCHEMATIC1(sch_1):INS83@ANALOG.L.Normal(chips)
C_C1            C1(1=0 2=N00124 ) CN @HW2_Q1.SCHEMATIC1(sch_1):INS108@ANALOG.C.Normal(chips)
I_I1            I1(+=N00157 -=0 ) CN @HW2_Q1.SCHEMATIC1(sch_1):INS202@SOURCE.IAC.Normal(chips)
_    _(V=V)
.ENDALIASES
